### ISSUE TITLE
s3Client never times out

### ISSUE THREAD

**Issue by toffer** [dogestry/dogestry#10]
If there's a loss of network connectivity while dogestry is transferring files to/from S3, then dogestry will just hang.

EDIT:

(My proposed solution below is wrong. I need to recognize when the transfer has stopped, not limit the amount of time that the transfer must complete in.)

~~The solution is to set the ConnectTimeout and ReadTimeout when creating the s3Client. Right now, both timeouts use the default value of 0, which is in effect, no timeout value at all.~~

**Comment by toffer** [comment]
Well, I was looking for a setting like "Idle Timeout", which would work similarly to these command line options for curl and wget:

    # Abort download if download rate is < 1 byte per second over 15 second period
    $ curl --speed-time 15 http://example.com
    
    # Abort download if no bytes are received for 15 seconds
    $ wget --read-timeout 15 http://example.com

But, it looks like the underlying `http.Client` only has a single Timeout value: http://golang.org/pkg/net/http/#Client.

Which means that while I can easily set a timeout for the S3 client that the entire transfer must complete by, there isn't an easy way to set a timeout value to recognize idle, or dead connections. So, I'm going to punt on this issue for now.

**Comment by didip** [comment]
Issue https://github.com/dogestry/dogestry/issues/56 may potential solve this problem. s3gof3r will retry N number of times then stop gracefully.
