### ISSUE TITLE
More resilient push command

### ISSUE THREAD

**Issue by devnatash** [dogestry/dogestry#102]
If a push command dies mid-push, the S3 image is left in a bad state, where the layer folder exists but its contents are not populated. 

When the push command is re-run, the bad layer is not replaced, because it's found to already exist and its file size is not checked. (https://github.com/dogestry/dogestry/blob/39b08c4e91ee1989e5e4cb5ea220a89acbfdf8b1/cli/push.go#L236) The image is unusable until it's manually deleted off S3 and re-pushed.

This could be fixed by comparing folder sizes as well as folder names when assessing which layers to push. Or, a "force" mode on the push command could overwrite any pre-existing layers.

**Comment by dselans** [comment]
This should no longer be an issue, as per: https://github.com/dogestry/dogestry/blob/master/remote/s3.go#L248

This was fixed a month or so ago - are you sure you are using the latest version of dogestry?
