### ISSUE TITLE
Rethink default value for docker host

### ISSUE THREAD

**Issue by toffer** [dogestry/dogestry#16]
In `config.GetDockerHost()`, if the DOCKER_HOST environment variable isn't found, the docker host is set to `tcp://localhost:2375`.

This is often not the correct value. Since the docker daemon binds to `unix:///var/run/docker.sock` by default, perhaps that would be a better default.

The other alternative that I think would be better than the current behavior is to not set a default value at all, which would force the user to set the DOCKER_HOST environment variable.

**Comment by relistan** [comment]
:+1: for @toffer's last suggestion
