### ISSUE TITLE
Handle downloading large files from S3 better

### ISSUE THREAD

**Issue by toffer** [dogestry/dogestry#17]
During the first part of the `dogestry pull` command, when dogestry downloads files from S3, I've seen several instances where downloading a large (1+ GB) layer.tar file will fail.

One time the failure resulted in an "Unexpected EOF" Error,. Another time, dogestry just hung midway through the download, never completing the download, but also never exiting.

To make this more robust, we should explore downloading large files in chunks (using the [range header](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectGET.html) in the AWS S3 REST API.)

**Comment by didip** [comment]
Issue: https://github.com/dogestry/dogestry/issues/56 will fix this problem.
