### ISSUE TITLE
Show progress for the dogestry pull command during sendTar

### ISSUE THREAD

**Issue by toffer** [dogestry/dogestry#19]
While the output of dogestry provides feedback on what's happening when files are being uploaded to or downloaded from S3, it doesn't show anything when importing the image into the docker hosts.

It would be helpful to see some indication of progress during this step.

**Comment by relistan** [comment]
Yes, this is annoying. :+1:

**Comment by didip** [comment]
On line: https://github.com/dogestry/dogestry/blob/master/cli/cli.go#L311, we can have a MultiWriter where one of them scans the bytes and print "... still going...".

**Comment by relistan** [comment]
So, what stops the progress meter from running? It seems like it's backgrounded without a quit chan.

https://github.com/dogestry/dogestry/blob/master/cli/cli.go#L316

**Comment by didip** [comment]
Because it's the final stage of `pull`, progress meter naturally stopped when the program exited.

**Comment by relistan** [comment]
Hmm, ok. That works as long as we never decide to do anything after that. I'd rather this stopped when the function returned.
