### ISSUE TITLE
Should we vendor all dependencies?

### ISSUE THREAD

**Issue by toffer** [dogestry/dogestry#31]
We currently vendor the `gcfg` package, but we don't vendor any of the others we depend on. I'm relatively new to Go, so I'm not sure if vendoring everything is the best practice, but, I started thinking about this when the goamz package moved to a new repo: #30.

These are the additional dependencies we would need to vendor:

"github.com/crowdmob/goamz/aws"
"github.com/fsouza/go-dockerclient"
"github.com/mitchellh/go-homedir"

In addition, these are the dependencies of our dependencies. (This may not be a complete list...Someone would need to double-check my work here.) Would vendoring these be required also?

"github.com/docker/docker/pkg"
"github.com/docker/docker/vendor/src/code.google.com/p/go/src/pkg/archive/tar"
"github.com/Sirupsen/logrus"

cc: @didip @relistan @amjith

**Comment by relistan** [comment]
I recommend `godep`: https://github.com/tools/godep . Doesn't solve the "moved to a new repo" issue, but does solve the versioning issue.

**Comment by didip** [comment]
Vendoring basically means we are forking it to our own directory structure. I don't think `go get` auto-magically figures out vendor packages. I'd say we should cross that bridge when we need to in the future.
