### ISSUE TITLE
Optimizations to exporting an image

### ISSUE THREAD

**Issue by amjith** [dogestry/dogestry#36]
Capturing @relistan's ideas for reducing the IO writes. 

1. Get the list of missing layers in S3 that needs to be uploaded. Start streaming the tar file from docker export for an image. For each file that is encountered in the streaming tar, only uncompress the files that are in the missing layers list, skip over the files that are not in the missing list. This way we only uncompress/write the missing layers to disk.

2. If item 1 is not possible, then export the docker image as a tar file into the temp folder. Instead of untaring the whole archive and picking the files we need to upload, only pull the necessary files from the tar archive directly, thus saving a disk write for untaring all the files. 

/cc @toffer

**Comment by didip** [comment]
Sounds legit.

**Comment by toffer** [comment]
Option 1 is a good idea, and should be totally doable...which means we can skip worrying about option 2!
