### ISSUE TITLE
must push container twice

### ISSUE THREAD

**Issue by chrisferry** [dogestry/dogestry#45]
After a push a remote pull results in "No such image"
After the second push the image is found.

See output here:
https://gist.github.com/chrisferry/55762840104b0ae075a9

**Comment by amjith** [comment]
Hi Chris,

A bunch of the core devs are at PyCon, so the response might be slow. But we'll take a look at it when we get back (next week). 

Thanks for reporting.

**Comment by toffer** [comment]
Chris,

I've experienced the exact same thing before. It perplexed me, too, so I did some digging to figure out what was going on, and the conclusion I reached is that we're seeing the effect of "eventual consistency" in how Amazon S3 works in the US Standard region.

As [described here](http://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html#ConsistencyMode), after you PUT an object into S3, you may not be able to read it immediately. Instead, you may have to wait for the change to propagate across multiple servers in Amazon's data centers first.

This only applies to using S3 in the US Standard region. Other regions have "read-after-write consistency", so objects are available immediately after uploading.

If I've diagnosed it correctly, that means that it wasn't the second `dogestry push` that made your upload "stick." Rather, it was just the passage of time.

To avoid this problem, you could either 1) Use a bucket in a different region that has "read-after-write consistency", or 2) Wait a few seconds before pulling the newly uploaded image :)

**Comment by chrisferry** [comment]
*doh* toffer that has to be the issue.  I'll run some more tests, but I think you hit the nail on the head.
