### ISSUE TITLE
Pushing a specific tag doesn't tag image correctly

### ISSUE THREAD

**Issue by johnae** [dogestry/dogestry#46]
At first I thought there was a problem with tagging in general but it seems to be about pushing specific tags rather.

It seems this works fine:

dogestry push s3://docker-s3-repo/images/?region=eu-west-1 quay.io/johnae/test

but this doesn't push the actual tags:

dogestry push s3://docker-s3-repo/images/?region=eu-west-1 quay.io/johnae/test:latest

it does, however, push tags if you simply execute the above command again.

**Comment by toffer** [comment]
@johnae Thanks for identifying this problem and opening an issue.

If you get a chance, you can check out PR #47 and verify that it fixes the problem.
