### ISSUE TITLE
Pushing an image will erase an identically-named image already in the bucket

### ISSUE THREAD

**Issue by alicegoldfuss** [dogestry/dogestry#48]
This seems like wanted behavior, except when rolling out across a company using a handful of shared buckets. Team 1 could push ImageA and Team 2 could also push an ImageA in ignorance of the former, therefore erasing the other team's work.

I propose Dogestry checks for identical images and offers a prompt "This push will overwrite image <IMAGE NAME> already on server. Okay to proceed y/n" with the addition of a -y force flag for scripted jobs.

**Comment by relistan** [comment]
Are you referring to the tag for the image (e.g. *latest*)? It should not change any images as they are all identified by the image ID.

**Comment by relistan** [comment]
I really think this is the expected behavior–equivalent to the way Docker push works. I'd rather we didn't do this.
