### ISSUE TITLE
Installation instructions on Wiki?

### ISSUE THREAD

**Issue by reu** [dogestry/dogestry#52]
I could not see any instructions on how to install dogestry. Also, doesn't you provide a download link to a dogestry binary? Or the only option would be to clone the repository and build it on my own?

**Comment by relistan** [comment]
Hi @reu . There should be at least a blurb in the README about installing it. But, like all projects on GitHub, the binaries are attached to the release:

https://github.com/dogestry/dogestry/releases

It's a statically linked binary, so get the one that works for you and just run it.

**Comment by reu** [comment]
Great! Thanks a lot @relistan!
