### ISSUE TITLE
panic: send on close channel - during 'dogestry push'

### ISSUE THREAD

**Issue by coopernurse** [dogestry/dogestry#64]
This could be user error, but my guess is there's at least a problem with some error handling code.  

version:

```
[root@localhost conf]# dogestry version
Dogestry 2.0.1

[root@localhost conf]# uname -a
Linux localhost.localdomain 3.10.0-123.20.1.el7.x86_64 #1 SMP Thu Jan 29 18:05:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

command:

`dogestry push s3://mybucket-docker?region=us-west-2 someuser/register`

error:

```
Pushing files to S3 remote:
2015/07/07 14:59:59 error when uploading to S3: 307: "Please re-send this request to the specified temporary endpoint. Continue to use the original request endpoint for future requests."
{"Status":"error", "Message": "Error when uploading to S3: 307: "Please re-send this request to the specified temporary endpoint. Continue to use the original request endpoint for future requests.""}
panic: send on closed channel

goroutine 131 [running]:
github.com/dogestry/dogestry/remote.func·002()
	/Users/didip/go/src/github.com/dogestry/dogestry/remote/s3.go:137 +0x24e
created by github.com/dogestry/dogestry/remote.(*S3Remote).Push
	/Users/didip/go/src/github.com/dogestry/dogestry/remote/s3.go:143 +0x499
```

**Comment by coopernurse** [comment]
A bit of searching suggests that this 307 error is returned by AWS when new buckets are created.  This applies to my case, as I just made a new bucket to store my docker images.  

This may be an issue with the S3 lib dogestry uses. Sounds like this 307 redirect case is something that lib should probably be handling.

The panic is still probably a dogestry issue though.  I haven't looked at the code to see what/why it's sending to the closed channel.

**Comment by coopernurse** [comment]
The panic is probably due to the early return here:

https://github.com/dogestry/dogestry/blob/master/remote/s3.go#L150

When that line executes, the `defer close(putFileErrChan)` runs which means any other active goroutines   will panic.

**Comment by didip** [comment]
Oh wow, thanks for the detailed research.

That early return is intended for dogestry to fail fast. But we didn't take into account other, currently running goroutines.

**Comment by coopernurse** [comment]
You're very welcome.  Also, I can confirm that the error related to the HTTP 307 status codes does go away in time.  I retried this today after my bucket had been created for 10+ hours, and the push command worked correctly.

So until the S3 lib used by dogestry is updated to handle that status code, it might be worth a note in the README warning folks that new S3 buckets may fail on push.

**Comment by didip** [comment]
WIP, See: https://github.com/dogestry/dogestry/commit/ae276502cba1ea199a8a7e0b62435feef786a967
