### ISSUE TITLE
Example config file,

### ISSUE THREAD

**Issue by noizu** [dogestry/dogestry#70]
I don't seem to see the config file mentioned in the readme.md file anywhere.  Could that reference be changed to a link?

**Comment by noizu** [comment]
Specifically I have a few s3fs mounts on my system with difference permission schemes so just setting the environment variables is a little clobberish for my setup ^_^.

**Comment by didip** [comment]
Ah, long time ago, the original code had a config file. But the structure of the fields inside that config file is too messy and untested. So, we deleted it not too long ago.

Small idea to help you, you can create a `.sh` file that's exports all the environment variables before executing dogestry.
