### ISSUE TITLE
Program hangs on failed upload

### ISSUE THREAD

**Issue by itzamna314** [dogestry/dogestry#73]
If one of the file uploads fails, dogestry will hang indefinitely.  This is because the channel closing logic in S3Remote.Push(..) is blocking, and will thus hang if any of the push goroutines has completed.

The for loop on line 170 of s3.go is the main culprit.  It makes a blocking write to each channel in goroutineQuitChans[].  A separate go routine has already been launched for each of those channels, and some of them may have completed successfully by the time the channel closing logic runs.  For each finished channel c, there is no go routine reading goroutineQuitChans[c].  This makes the channel write on line 171 block forever.

I believe that the write to the quit channels should be changed to be non-blocking.  I've been able to fix this on my local branch with the following change:

```
for i := 0; i < numGoroutines; i++ {
	select {
	case goroutineQuitChans[i] <- true:
	default:
}				
```

**Comment by dselans** [comment]
I believe this commit should resolve your issues: https://github.com/dogestry/dogestry/commit/d88911b053451458d6bb1a03871036fb4e62f4ed

Can you please try out the latest dogestry release and let me know if you're still seeing the problem?

**Comment by dselans** [comment]
Closing this out - this should no longer be an issue.

**Comment by itzamna314** [comment]
Thanks!  I've been working off of a fork that hosts our images in azure blob storage instead of s3.  When I get a chance I'll rebase and make sure this fix resolves my issue.  Looking at the fix, I believe it will do the trick.
