### ISSUE TITLE
push/pull doesn't respect <path name> per documentation

### ISSUE THREAD

**Issue by bick4ord** [dogestry/dogestry#78]
The doc says:

`$ dogestry push s3://<bucket name>/<path name>/?region=us-east-1 <image name>`

I tried making changes to `<path name>` but it appears to be ignored.  The images and repositories directories are always created in the root of the S3 bucket.

Am I doing something wrong?

It would be nice if the path was working, since it allows managing multiple registries without the overhead of managing a bucket for each (and IAM roles, etc).

**Comment by didip** [comment]
Ugh... this is our bad, we actually deprecated that feature a long time ago and the docs have not been updated. Sorry.

**Comment by didip** [comment]
The readme docs have since been updated.
