### ISSUE TITLE
Cannot connect to Docker endpoint

### ISSUE THREAD

**Issue by Shadowfen** [dogestry/dogestry#88]
Installed from binary.

Why is it trying to use locallhost instead of localhost?

dogestry push s3://xxx-xxx/?region=us-west-2 yyyyyy:latest
WorkDir: /tmp/dogestry078930855/yyyyyy_latest
Using docker endpoint for push: tcp://locallhost:2375
Error getting image history: cannot connect to Docker endpoint
2015/12/01 12:23:03 cannot connect to Docker endpoint

**Comment by dselans** [comment]
@Shadowfen Are you sure your $DOCKER_HOST is not pointing to that?

Do `echo $DOCKER_HOST` and see what it points to.

**Comment by Shadowfen** [comment]
That was it.

Thank you.

D

**Comment by t3ndai** [comment]
hello I'm facing the same issue
installed via brew cask

dogestry push s3://xxxxxxx/?region=us-east-1 nginx
WorkDir: /var/folders/xg/zcrb3kdd6pvc2ddpjqts_xnw0000gn/T/dogestry645465905/nginx
Using docker endpoint for push: tcp://localhost:2375
Remote: s3(bucket=xxxxxxx, region=us-east-1)
Error getting image history: cannot connect to Docker endpoint
2017/05/07 20:51:56 cannot connect to Docker endpoint

**Comment by relistan** [comment]
@t3ndai So dogestry stopped working with versions of Docker after 1.9 because the image ID formats are no longer compatible with how Dogestry needs to look them up. Even if you get this working it probably won't work unless you're using an older Docker.
