### ISSUE TITLE
If dogestry server check fails due to one host down, deploy still attempted

### ISSUE THREAD

**Issue by intjonathan** [dogestry/dogestry#94]
If one of the hosts in the deploy is down, the deploy will fail regardless of the image state on the remaining machines. This is especially painful in non-dogestry-server deploys, where it may get halfway through image discovery on a list of 20 machines before realizing the deploy should be aborted.

Consider adding a sanity check at the front to find out if docker is available on all the hosts in the deploy.

**Comment by dselans** [comment]
Great idea! Will add in next release.
